language: node_js
node_js:
  - 14  
deploy:
  skip_cleanup: true

script: 'true'

before_install:
  - npm i -g npm@6.14.9
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true